### ISSUE TITLE
Hotspot to Portuguese Translation

### ISSUE THREAD

**Issue by coreosbr** [TabrizLi/Mikrotik-RTL-Theme#1]
Hello, Can you translate The Hotspot to Portuguese (pt_BR)? I have difficulty. In Brazil, the fields to the right.

Thank you!!!

**Comment by MirHamit** [comment]
I don't know Portuguese,  but I will translate it to English,  is that ok to you ?

**Comment by coreosbr** [comment]
ok

**Comment by coreosbr** [comment]
thanks for listening. My email: ars0306@gmail.com
