### ISSUE TITLE
submit bottom not working

### ISSUE THREAD

**Issue by miladsh697** [TabrizLi/Mikrotik-RTL-Theme#2]
salam
dokme submit vorod baray goshi kar nemikonad bar roy system ya ke mode decktop mode faal bashe kar mikone vali roye mode goshi mobile(responsive) kar nemikonad

**Comment by MirHamit** [comment]
تو اصلاحیه جدید مشکل برطرف شد و میتونین فایل رو دوباره آپلود کنین روی روتر و استفاده کنین
لطفا بررسی کنین و نتیجه رو بگین
