### ISSUE TITLE
چگونگی تغییر در صفحه ریدایرکت

### ISSUE THREAD

**Issue by komeylgivechi** [TabrizLi/Mikrotik-RTL-Theme#3]
سلام خدمت شما
متشکرم از قالب بسیار زیباتون
سوالی که داشتم این بود که بعد از ورود به صفحه استتوس هدایت میشیم و بعد از اون به شکل خودکار به صفحه
msn.com
چطوری میتونم تغییری در این وضعیت ایجاد کرد که به صفحه 
msn.com 
نرود

**Comment by MirHamit** [comment]
این کار رو خود مرورگرتون انجام میده
به عنوان مثال وقتی مرورگر اینترنت اکسپلورر رو باز میکنین به صورت پیشفرض به صفحه 
msn.com
میخواد بره که میکروتیک اون رو به صفحه ورود انتقال میده، بعد از وارد کردن رمز عبور و احراز هویت دوباره به سمت همون سایت منتقل میشه

این قالب هیچ گونه دخل و تصرفی توی هدایت کاربر به جایی نداره
بازم اگه مشکلی یا سوالی داشتین در خدمتیم
